# Generated by Django 4.0.1 on 2024-01-23 07:43

import apps.advertisement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADVTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('slug', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('coin', models.IntegerField(blank=True, default=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('limit_char', models.IntegerField(blank=True, default=500, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=apps.advertisement.models.path_file_adv)),
                ('contuct', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('status', models.CharField(blank=True, choices=[('publish', 'Publish ✅'), ('reject', 'Reject ❌'), ('wait_for_pay', 'Wait For Pay 💰'), ('wait_for_publish', 'Wait For Publish ⌛️')], default='unknow', max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('warning_tag', models.BooleanField(blank=True, default=False, null=True)),
                ('is_expired', models.BooleanField(blank=True, default=False, null=True)),
                ('type_adv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_advertisements', to='advertisement.advtypes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
