# Generated by Django 4.0.1 on 2024-01-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(blank=True, choices=[('publish', 'Publish ✅'), ('reject', 'Reject ❌'), ('wait_for_pay', 'Wait For Pay 💰'), ('wait_for_publish', 'Wait For Publish ⌛️')], default='wait_for_pay', max_length=30, null=True),
        ),
    ]
