# Generated by Django 4.0.1 on 2024-01-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisement_contuct_alter_advertisement_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADVTypes',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='type_adv',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_advertisements', to='advertisement.category'),
        ),
    ]
