# Generated by Django 4.0.1 on 2024-01-23 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisement', '0003_alter_advertisement_contuct_alter_advertisement_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount : ﷼')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created Payment')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Paid ?')),
                ('getway', models.CharField(blank=True, default='zarinpal', max_length=70, null=True, verbose_name='Getway Name')),
                ('transaction_id', models.CharField(blank=True, max_length=70, null=True, verbose_name='Transaction Id')),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertisement_payments', to='advertisement.advertisement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
